### ISSUE TITLE
AWI reference causes `isodoc` gem to crash

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#117]
See https://github.com/relaton/relaton-iso/issues/70 .

---

```adoc

[bibliography]
== Normative References

* [[[ISO34000,ISO 34000]]], _Date and time -- Concepts and vocabulary_

[[terms]]
[source=ISO34000]
== Terms and Definitions
...

```

Error:

```sh
character content of element "from" invalid; must be a year @ 1644:40
character content of element "from" invalid; must be a year @ 1689:44
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
TypeError: no implicit conversion of nil into String
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/inline.rb:84:in `+'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/inline.rb:84:in `eref_parse'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/to_word_html.rb:205:in `parse'
```

Line 1644 is exactly `<copyright>`. The value should not be `copyright value unknown`, it probably should be "unknown".

<img width="653" alt="Screen Shot 2019-09-04 at 4 14 08 PM" src="https://user-images.githubusercontent.com/11865/64237485-0709b500-cf2f-11e9-8214-75e7541f2c5d.png">

This task is to fix the `isodoc` gem to accept the `unknown` value.

**Comment by ronaldtse** [comment]
@opoudjis please also remember to add a spec. Thanks.

**Comment by ronaldtse** [comment]
So I found a second instance of the same issue:

```xml
<terms id="terms" obligation="normative"><title>Terms and definitions</title><p>For the purposes of this document, the terms and definitions 
  given in <eref bibitem="ISO19160-1"/> and the following apply.</p>
```

This is from https://github.com/CalConnect/csd-digital-addresses/

The specific syntax is:

```adoc
[bibliography]
== Normative References

* [[[ISO19160-1,ISO 19160-1]]], _Addressing -- Part 1: Conceptual Model_

[[terms]]
[source=ISO19160-1]
== Terms and definitions
```

**Comment by ronaldtse** [comment]
(This is a regression in isodoc -- it used to work)
