### ISSUE TITLE
(URGENT) Data URLs breaking

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#119]
We are processing Data URIs in metanorma-standoc as source. 

These files need to get saved to disk temporarily during isodoc processing, so that the gem can work out the pixel size of the images, and whether they need to be shrunk.

Along the road in processing them, they are breaking in Windows: the file is not saving to disk. They are breaking either because they are not specified as having an explicit MIME type, or because the resulting file name is too long.

This issue is happening to three of the four documents included in https://github.com/metanorma/mn-samples-itu. You will see the issue when you start running make.

Ronald thinks the real solution to this is to save any temporary files to disk in /tmp, per https://github.com/metanorma/metanorma-standoc/issues/53 . I think the real solution is to hunt down and destroy all copies of Windows in existence, but I hope you have a more workable solution.

The code involved is lib/isodoc/html_function/html.rb:

````
def image_localfile(i)
      if /^data:image/.match i["src"]
        save_dataimage(i["src"], false)
      else
        File.join(@localdir, i["src"])
      end
    end

    ....

    def move_image1(i)
      matched = /\.(?<suffix>[^. \r\n\t]+)$/.match i["src"]
      uuid = UUIDTools::UUID.random_create.to_s
      fname = "#{uuid}.#{matched[:suffix]}"
      new_full_filename = File.join(tmpimagedir, fname)
      local_filename = image_localfile(i)
      FileUtils.cp local_filename, new_full_filename
      i["src"] = File.join(rel_tmpimagedir, fname)
    end
````

**Comment by ronaldtse** [comment]
Here's the trace:

https://ci.appveyor.com/project/Metanorma/mn-samples-itu/build/job/1ch37qifxe8wgpyp

```
element "itu-standard" incomplete; missing required element "bibliography" @ 2003:16
461No label has been processed for ID b-Eschbach 2001
462No label has been processed for ID [b-Eschbach 2001]
463C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/function/utils.rb:155:in `initialize': Invalid argument @ rb_sysopen - sources/Z.100-201811-AnnF1_htmlimages/3d82a4d9-3090-4c54-b83e-dde137eb792a.* (Errno::EINVAL)
464	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/function/utils.rb:155:in `open'
465	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/function/utils.rb:155:in `save_dataimage'
466	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/html_function/html.rb:259:in `image_localfile'
467	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/html_function/html.rb:249:in `block in move_images'
468	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.4-x86-mingw32/lib/nokogiri/xml/node_set.rb:238:in `block in each'
469	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.4-x86-mingw32/lib/nokogiri/xml/node_set.rb:237:in `upto'
470	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.4-x86-mingw32/lib/nokogiri/xml/node_set.rb:237:in `each'
471	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/html_function/html.rb:248:in `move_images'
472	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/html_function/html.rb:47:in `toHTML'
473	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/html_function/html.rb:33:in `postprocess'
474	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/convert.rb:169:in `convert'
475	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/isodoc-ed77a3f7c9c9/lib/isodoc/html_convert.rb:17:in `convert'
476	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bundler/gems/metanorma-itu-ed404e9eee80/lib/metanorma/itu/processor.rb:32:in `output'
477	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:192:in `block in process_extensions'
478	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `each'
479	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:183:in `process_extensions'
480	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:20:in `compile'
481	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-cli-1.2.6/lib/metanorma/cli/compiler.rb:27:in `compile_file'
482	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-cli-1.2.6/lib/metanorma/cli/compiler.rb:13:in `compile'
483	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-cli-1.2.6/lib/metanorma/cli/compiler.rb:17:in `compile'
484	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-cli-1.2.6/lib/metanorma/cli/command.rb:34:in `compile'
485	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
486	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
487	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
488	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
489	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-cli-1.2.6/lib/metanorma/cli.rb:60:in `start'
490	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/gems/metanorma-cli-1.2.6/exe/metanorma:20:in `<top (required)>'
491	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bin/metanorma:23:in `load'
492	from C:/projects/mn-samples-itu/vendor/bundle/ruby/2.5.0/bin/metanorma:23:in `<main>'
493[relaton] processor "relaton_ogc" registered
494make: *** [Makefile.win:47: sources/Z.100-201811-AnnF1.xml] Error 1
495
```

The cause of this is probably the file could not be saved. And the cause of that I suspect is the code is trying to save the file as: `sources/Z.100-201811-AnnF1_htmlimages/3d82a4d9-3090-4c54-b83e-dde137eb792a.*` instead of a real file extension.

https://github.com/metanorma/isodoc/blob/e51750776101594e92b77a24bbf08a4bd540c35f/lib/isodoc/html_function/html.rb#L272-L280

In particular, notice this function has no error checking -- it is easy for the file to end up with no extension.

https://github.com/metanorma/isodoc/blob/e51750776101594e92b77a24bbf08a4bd540c35f/lib/isodoc/html_function/html.rb#L275

Please rewrite these two functions so that they do actual error checking and generate proper files. And we need to add a test for this.

(the mn-samples-itu files use `image::data/image;xxxx` images, this is probably the reason why the MIME type is not found)

This is highest priority. Thanks.

**Comment by opoudjis** [comment]
I have mitigated this issue through https://github.com/metanorma/metanorma-standoc/issues/120, which tries to prevent `.*` ever turning up in XML.

**Comment by opoudjis** [comment]
I have switched to tempfile in standoc for saving data urls to disk. You can try plugging it in to replace save_dataimage in isodoc

````
def datauri2mime(uri)
         %r{^data:image/(?<imgtype>[^;]+);base64,(?<imgdata>.+)$} =~ uri
         file = Tempfile.new(["hello", ".jpg"])
         file.binmode
         file.write(Base64.strict_decode64(imgdata))
         file.rewind
         type = MimeMagic.by_magic(file)
         file.close
         file.unlink 
         [type]
       end
````

**Comment by ronaldtse** [comment]
Here's a cleaner version of the Tempfile:

```ruby
def datauri2mime(uri)
  %r{^data:image/(?<imgtype>[^;]+);base64,(?<imgdata>.+)$} =~ uri
  Tempfile.open(["imageuri", ".#{imgtype}"]) do |file|
    file.binmode
    file.write(Base64.strict_decode64(imgdata))
...
  ensure
    file.close!
  end
...
end
```

**Comment by CAMOBAP795** [comment]
Tested on win10

[output.txt](https://github.com/metanorma/isodoc/files/3664114/output.txt)

**Comment by opoudjis** [comment]
@CAMOBAP795 I'm happy to take this back on for myself. Can you confirm please that you did not need to fix this in order to get Metanorma working for Nermina and Manuel?

**Comment by opoudjis** [comment]
This issue will be merged into https://github.com/metanorma/isodoc/issues/122 once @CAMOBAP795 replies...

**Comment by CAMOBAP795** [comment]
@opoudjis I just didn't notice any issues during testing on windows (I have tested on mn-samples-itu)

**Comment by opoudjis** [comment]
Merging into #122
