### ISSUE TITLE
CSS override

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#270]
CSS overrides seem to be a persistent requirement out of ISO, so I'll implement a CSS override argument, with a document attribute added and reading in a CSS, to be placed after the flavour CSS.

**Comment by ronaldtse** [comment]
Broken:

```
No such file or directory @ rb_sysopen - html_override.css
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/css.rb:23:in `initialize'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/css.rb:23:in `open'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/css.rb:23:in `populate_css'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/html_function/html.rb:10:in `block (2 levels) in convert1'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/html_function/html.rb:8:in `block in convert1'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/function/utils.rb:32:in `noko'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/html_function/html.rb:7:in `convert1'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-iso-021cadba7173/lib/isodoc/iso/base_convert.rb:13:in `convert1'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/convert.rb:158:in `convert'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/isodoc-15e1c5fc29db/lib/isodoc/html_convert.rb:24:in `convert'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-iso-021cadba7173/lib/metanorma/iso/processor.rb:47:in `output'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-2becce1b07e7/lib/metanorma/compile.rb:265:in `block in process_extensions'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-2becce1b07e7/lib/metanorma/compile.rb:250:in `each'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-2becce1b07e7/lib/metanorma/compile.rb:250:in `process_extensions'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-2becce1b07e7/lib/metanorma/compile.rb:29:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/compiler.rb:45:in `compile_file'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/compiler.rb:30:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/compiler.rb:35:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/site_generator.rb:81:in `compile'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/site_generator.rb:28:in `each'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/site_generator.rb:28:in `generate'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/site_generator.rb:23:in `generate'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli/commands/site.rb:25:in `generate'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/lib/metanorma/cli.rb:67:in `start'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/metanorma-cli-5f09783e2e83/exe/metanorma:20:in `<top (required)>'
```

Refer to CI failure in https://github.com/metanorma/annotated-express/pull/84

**Comment by opoudjis** [comment]
Making locations of stylesheet location attributes, as well as stylesheet override location attributes, relative to the root document.

**Comment by opoudjis** [comment]
And we are going to pass the location of the original Asciidoc source to isodoc in metanorma, since metanorma compilation of isodoc under site building does not know where the original source is, and is thus looking for stylesheets in the target directory.
