### ISSUE TITLE
Build error: wrong number of arguments (given 3, expected 2) 

### ISSUE THREAD

**Issue by w00lf** [metanorma/isodoc#332]
When trying to render the latest master ogc-citygml-xmi, backtrace:

```sh
/Users/mikhailtretiakov/.rvm/gems/ruby-2.7.3/bundler/gems/isodoc-665ded251181/lib/isodoc/presentation_function/inline.rb:182:in `concept_render' 
/Users/mikhailtretiakov/.rvm/gems/ruby-2.7.3/gems/metanorma-iso-1.9.3/lib/isodoc/iso/presentation_xml_convert.rb:128:in `concept_term' /Users/mikhailtretiakov/.rvm/gems/ruby-2.7.3/gems/metanorma-iso-1.9.3/lib/isodoc/iso/presentation_xml_convert.rb:117:in `block in concept' 
/Users/mikhailtretiakov/.rvm/gems/ruby-2.7.3/gems/nokogiri-1.11.7-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each' 
/Users/mikhailtretiakov/.rvm/gems/ruby-2.7.3/gems/nokogiri-1.11.7-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
```

**Comment by ronaldtse** [comment]
Try running `bundle update`?

**Comment by w00lf** [comment]
From @opoudjis :

Today you should use metanorma-iso branch features/concept-linkmention

Release is tomorrow

and all this will be resolved then

**Comment by opoudjis** [comment]
As communicated with Mikl: need to pull metanorma-iso PR features/concept-linkmention, since this is a breaking change in isodoc. Will be resolved in release tomorrow.
