### ISSUE TITLE
(URGENT) Crash in ISO document: ISO 19135

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#426]
This occurs when compiling [ISO 19135](https://github.com/metanorma/iso-19135). Just run `bundle exec metanorma site generate`.

```
        node = node.parent
                   ^^^^^^^
Did you mean?  parent=
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/class_utils.rb:70:in `nearest_block_parent'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/class_utils.rb:77:in `start_of_sentence'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/function/utils.rb:15:in `start_of_sentence'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/xrefs.rb:108:in `capitalise_xref1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/xrefs.rb:104:in `capitalise_xref'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/xrefs.rb:31:in `anchor_linkend1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.1.6/lib/isodoc/iso/presentation_xref.rb:127:in `anchor_linkend1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/xrefs.rb:20:in `anchor_linkend'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/inline.rb:16:in `get_linkend'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/inline.rb:200:in `xref1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/inline.rb:184:in `block in xref'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_function/inline.rb:184:in `xref'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_xml_convert.rb:65:in `inline'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_xml_convert.rb:30:in `conversions'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/presentation_xml_convert.rb:19:in `convert1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.1.6/lib/isodoc/iso/presentation_xml_convert.rb:17:in `convert1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.2.0/lib/isodoc/convert.rb:208:in `convert'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.1.6/lib/metanorma/iso/processor.rb:67:in `output'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:157:in `process_output_unthreaded'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:144:in `process_exts1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:118:in `process_ext'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:106:in `block in process_exts'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:105:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:105:in `process_exts'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.4.12/lib/metanorma/compile.rb:37:in `compile'
```

**Comment by ronaldtse** [comment]
No longer failing at:
```
    metanorma-iso (2.1.7)
      metanorma-standoc (~> 2.2.0)
```
