### ISSUE TITLE
Document with attachment raises the error `Invalid argument @ dir_s_mkdir`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/isodoc#580]
Related issues: https://github.com/metanorma/mn-native-pdf/issues/694, https://github.com/metanorma/iso-10303/issues/208.

Simple source document ([ISO_Attachment.zip](https://github.com/user-attachments/files/15888756/ISO_Attachment.zip)):
```adoc
== Scope

Test case: [file1]

[bibliography]
== Bibliography

* [[[ISO3696,ISO 3696]]], _Water for analytical laboratory use -- Specification and test methods_

* [[[file1,attachment:(schemas/action_schema.exp)]]]
```

`Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"

gem "sassc"
```

OS: Windows 10 64-bit

Current folder: `D:\Work\Metanorma\ISO_Attachment`

```
bundle update
bundle exec metanorma -t iso -x presentation test.attachment.adoc 
```

Error:
```
[relaton-iso] (ISO 3696) Fetching from Relaton repository ...
[relaton-iso] Downloaded index from https://raw.githubusercontent.com/relaton/relaton-data-iso/main/index-v1.zip
[relaton-iso] (ISO 3696) Found: `ISO 3696:1987`
Style: Normative references missing
Style: Terms & definitions missing
Style: Initial section must be (content) Foreword
Style: Prefatory material must be followed by (clause) Scope
Style: Document must contain at least one clause
Style: Document must contain clause after Terms and Definitions
Style: Only annexes and references can follow clauses
Style: Document must include (references) Normative References
Style: Final section must be (references) Bibliography
C:/tools/ruby31/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir'
C:/tools/ruby31/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
C:/tools/ruby31/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
C:/tools/ruby31/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
C:/tools/ruby31/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
C:/tools/ruby31/lib/ruby/3.1.0/fileutils.rb:211:in `each'
C:/tools/ruby31/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-bedf78b3cfe0/lib/isodoc/presentation_function/metadata.rb:18:in `attachments_extract'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-bedf78b3cfe0/lib/isodoc/presentation_function/metadata.rb:6:in `metadata'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-bedf78b3cfe0/lib/isodoc/presentation_xml_convert.rb:42:in `conversions'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-bedf78b3cfe0/lib/isodoc/presentation_xml_convert.rb:28:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-a677635db3b4/lib/isodoc/iso/presentation_xml_convert.rb:23:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-bedf78b3cfe0/lib/isodoc/convert.rb:168:in `convert'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-a677635db3b4/lib/metanorma/iso/processor.rb:69:in `output'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:184:in `process_output_unthreaded'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:170:in `process_exts1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:143:in `process_ext'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:125:in `block in process_exts_run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:124:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:124:in `process_exts_run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:119:in `process_exts'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:35:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/compiler.rb:30:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/compiler.rb:35:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/command.rb:248:in `compile_document'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/command.rb:48:in `block in compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/command.rb:48:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli/command.rb:48:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/lib/metanorma/cli.rb:34:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/exe/metanorma:25:in `block in <top (required)>'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.1/exe/metanorma:43:in `<top (required)>'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<main>'
Invalid argument @ dir_s_mkdir - D:/Work/Metanorma/ISO_Attachment/_D:
```

**Comment by opoudjis** [comment]
I'm not sure, but I think making sure the filename in Presentation XML is the basename will take care of it. @Intelligent2013 Please confirm.

**Comment by Intelligent2013** [comment]
@opoudjis thank you! It's working now.
