### ISSUE TITLE
Crash in mn-samples-plateau on generating indexes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#599]
isodoc crashes with this quoted PR. The only thing this PR does is adding an index.

```
Style: (ID tocW_02): More than 1 ordered list in a numbered clause
gems/3.3.0/gems/metanorma-iso-2.8.4/lib/isodoc/iso/index.rb:107:in `see_lbl'
gems/3.3.0/gems/metanorma-iso-2.8.4/lib/isodoc/iso/index.rb:46:in `index_entries_opt'
gems/3.3.0/gems/metanorma-iso-2.8.4/lib/isodoc/iso/index.rb:52:in `index_entries'
gems/3.3.0/gems/metanorma-iso-2.8.4/lib/isodoc/iso/index.rb:28:in `block (2 levels) in index1'
gems/3.3.0/gems/metanorma-iso-2.8.4/lib/isodoc/iso/index.rb:27:in `each'
gems/3.3.0/gems/metanorma-iso-2.8.4/lib/isodoc/iso/index.rb:27:in `block in index1'
```

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-plateau/issues/156#issuecomment-2322737930_

**Comment by opoudjis** [comment]
Already fixed in https://github.com/metanorma/mn-samples-plateau/issues/91
