### ISSUE TITLE
Error when running `suma build` on `iso-10303` with isodoc v2.12.4

### ISSUE THREAD

**Issue by kwkwan** [metanorma/isodoc#626]
In project `iso-10303`, when running
```
bundle exec suma build metanorma-srl.yml
```
An error has been occurred as following:
```
~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/lutaml-model-0.3.30/lib/lutaml/model/key_value_mapping.rb:12:in `map': unknown keyword: :using (ArgumentError)
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/collection_manifest.rb:17:in `block in <class:CollectionManifest>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/lutaml-model-0.3.30/lib/lutaml/model/serialize.rb:98:in `instance_eval'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/lutaml-model-0.3.30/lib/lutaml/model/serialize.rb:98:in `block (2 levels) in <module:ClassMethods>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/collection_manifest.rb:14:in `<class:CollectionManifest>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/collection_manifest.rb:8:in `<module:Suma>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/collection_manifest.rb:7:in `<top (required)>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/collection_config.rb:5:in `require_relative'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/collection_config.rb:5:in `<top (required)>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/processor.rb:6:in `require_relative'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/processor.rb:6:in `<top (required)>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/cli.rb:5:in `require_relative'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/lib/suma/cli.rb:5:in `<top (required)>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/exe/suma:4:in `require'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bundler/gems/suma-7b353023bc59/exe/suma:4:in `<top (required)>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bin/suma:25:in `load'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/bin/suma:25:in `<top (required)>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:58:in `load'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:23:in `run'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/cli.rb:455:in `exec'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/cli.rb:35:in `dispatch'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/cli.rb:29:in `start'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/exe/bundle:28:in `block in <top (required)>'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from ~/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/bundler-2.5.17/exe/bundle:20:in `<top (required)>'
	from ~/.rbenv/versions/3.1.5/bin/bundle:25:in `load'
	from ~/.rbenv/versions/3.1.5/bin/bundle:25:in `<main>'
```

If `gem "isodoc", "2.12.1"` is specified in `Gemfile`, there will be no such error.

**Comment by opoudjis** [comment]
@kwkwan if you want me to pay attention, you need to assign me the issue. 

This is not my problem. This is a problem with lutaml-model not supporting Shale's "using" keyword, which has been raised in https://github.com/lutaml/lutaml-model/issues/88 . As you will see from discussion there, @ronaldtse is proposing a completely different way of dealing with custom mappings not specific to a single attribute.

In any case, these likely can (and therefore MUST) be rewritten using lutaml-model's "with" keyword. I refer you to https://github.com/lutaml/lutaml-model/?tab=readme-ov-file#attribute-serialization-with-custom-methods . You will need to rewrite the Shale mappings in suma to confirm with lutaml-model, and if there is something that lutaml-model cannot cope with, you will need to take it up with Hassan.
